name: Patch OTA with Magisk

on:
  push:
    branches:
      - main

jobs:
  patch-ota:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download OTA update
      run: |
        wget -O ota.zip https://dl.google.com/developers/android/baklava/images/factory/bluejay_beta-bp21.241121.009-factory-cf5e025e.zip

    - name: Install Magisk
      run: |
        wget -O magisk.apk https://github.com/topjohnwu/Magisk/releases/download/v28.1/Magisk-v28.1.apk
        unzip magisk.apk -d magisk

    - name: Patch OTA with Magisk
      run: |
        java -jar magisk/magisk.jar patch ota.zip

    - name: Upload patched image
      uses: actions/upload-artifact@v3
      with:
        name: patched-ota
        path: magisk/output/patched_image.img
