name: Patch OTA with Magisk

on:
  push:
    branches:
      - main

jobs:
  patch-ota:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download OTA update
      run: |
        wget -O ota.zip https://dl.google.com/developers/android/baklava/images/factory/bluejay_beta-bp21.241121.009-factory-cf5e025e.zip

    - name: Verify OTA checksum
      run: |
        echo "cf5e025ea269a767f40ce568453768aec23833eb7350762b7f3d7c38babc0b7f ota.zip" | sha256sum -c -

    - name: Download Magisk
      run: |
        wget -O magisk.apk https://github.com/topjohnwu/Magisk/releases/download/v28.1/Magisk-v28.1.apk

    - name: Extract Magisk
      run: |
        unzip magisk.apk -d magisk

    - name: List files in magisk directory
      run: |
        ls -la magisk

    - name: Patch OTA with Magisk
      run: |
        if [ -f magisk/magisk.jar ]; then
          java -jar magisk/magisk.jar patch ota.zip
        else
          echo "magisk.jar not found"
          exit 1
        fi

    - name: Upload patched image
      uses: actions/upload-artifact@v3
      with:
        name: patched-ota
        path: magisk/output/patched_image.img
